parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/DTO/'
            - '../src/Kernel.php'

    # comment the lines below if you want to work with tagged locator instead
    _instanceof:
        App\Service\User\UserTypeInterface:
            tags:
                - 'app.user_type'
    App\Service\Locator\UserLocator:
        arguments:
            - !tagged_locator {tag: 'app.user_type'}